---
- hosts: python
  roles:
    - role: common
      user:
        name: yujunz
        comment: Yujun Zhang
        shell: /bin/zsh
        groups: sudo
        append: yes
    - role: pyenv
      pyenv_runcom: ~/.zshrc
      pyenv_virtualenv: true
      pyenv_versions:
        - 2.7.12
        - 3.5.2
      pyenv_default_versions:
        - 2.7.12
        - 3.5.2
