---
- hosts: devspaces
  tasks:
  - name: apt cache update
    become: true
    apt: update_cache=yes cache_valid_time=3600
  - name: all packages updated to latest version
    become: true
    apt: upgrade=dist
  - name: packages for development installed
    become: true
    apt: name={{ item }} state=latest
    with_items:
      - zsh
      - git
      - python
  - name: user configuration
    become: true
    user: name=yujunz comment="Yujun Zhang" shell=/bin/zsh groups=sudo append=yes
  - name: ensure pyenv is installed
    command: "curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash"
